# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-12 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allocation', '0002_aggregatedportfolio_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectivePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectivePortfolioAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quote', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.Asset')),
                ('objective_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.ObjectivePortfolio')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_required', models.FloatField()),
                ('objective', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allocation.Objective')),
                ('objective_portfolio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.ObjectivePortfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quote', models.FloatField()),
                ('aggregated_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.AggregatedPortfolio')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='UserResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founds', models.FloatField()),
                ('monthly_savings', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
