# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-12 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_objectiveportfolio_objectiveportfolioasset_objectivesolution_portfolioasset_userresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivesolution',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.Objective'),
        ),
        migrations.AlterField(
            model_name='objectivesolution',
            name='objective_portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocation.ObjectivePortfolio'),
        ),
        migrations.AlterField(
            model_name='userresource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
