# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_auto_20190212_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectivesolution',
            name='objective_portfolio',
        ),
        migrations.AlterField(
            model_name='objectiveportfolioasset',
            name='objective_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.ObjectiveSolution'),
        ),
        migrations.DeleteModel(
            name='ObjectivePortfolio',
        ),
    ]
