# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-12 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_auto_20190212_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectiveportfolioasset',
            old_name='objective_portfolio',
            new_name='objective_solution',
        ),
    ]
