# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_auto_20190212_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectivesolution',
            name='feasible',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
