# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0007_objectivesolution_feasible'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectivesolution',
            name='expected_return',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectivesolution',
            name='expected_risk',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
